name: Tom Chung
description: Tom Chung is an independent industrial designer focused on material objects and space. He is based in Toronto, Canada.

url: "http://localhost:4000"

markdown: rdiscount
permalink: /projects/:title/
highlighter: pygments